### ISSUE TITLE
Panphon feature table encoding error

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/FluentAI#119]
**Describe the bug**

When running main.py
```
Traceback (most recent call last):
  File "e:\GitHub Large Projects\FluentAI\fluentai\services\card_gen\main.py", line 7, in <module>
    from fluentai.services.card_gen.mnemonic.word2mnemonic import generate_mnemonic
  File "E:\GitHub Large Projects\FluentAI\fluentai\services\card_gen\mnemonic\word2mnemonic.py", line 14, in <module>
    from fluentai.services.card_gen.mnemonic.phonetic.phonetic import top_phonetic
  File "E:\GitHub Large Projects\FluentAI\fluentai\services\card_gen\mnemonic\phonetic\phonetic.py", line 7, in <module>
    from fluentai.services.card_gen.mnemonic.phonetic.ipa2vec import panphon_vec, soundvec
  File "E:\GitHub Large Projects\FluentAI\fluentai\services\card_gen\mnemonic\phonetic\ipa2vec.py", line 20, in <module>
    ft = panphon.FeatureTable()
  File "G:\Anaconda\envs\FluentAI\lib\site-packages\panphon\featuretable.py", line 62, in __init__
    self.segments, self.seg_dict, self.names = self._read_bases(bases_fn, self.weights)
  File "G:\Anaconda\envs\FluentAI\lib\site-packages\panphon\featuretable.py", line 81, in _read_bases
    header = next(reader)
  File "G:\Anaconda\envs\FluentAI\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 970: character maps to <undefined>
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by StephanAkkerman** [comment]
Fixed by following these instructions: https://github.com/microsoft/knack/pull/178
